### ISSUE TITLE
Changing the jump from a CSS animation to be defined by gravity and velocity

### ISSUE THREAD

**Issue by ChrisGenschow** [ChrisGenschow/Dinosaur-game#3]
I've turned the css animation off for the heart, so it shouldn't trigger when you jump.
Then in the character.js I tried defining a new jump, which should happen, when pressing space.
I've based the jump off of gravity and velocity, which I've defined in the same js. Currently the event triggers, when I'm looking at the inspector tool, but the character doesn't move >:C

**Comment by beutnagel** [comment]
What happens is almost what you wanted to happen, i.e.
- Spacebar initiates a jump
- handleJump increments the `--buttom`
- `setCustomProperty` does its job
- So the `img.character` gets the custom property value assigned as an inline style

HOWEVER, that value does not get applied as you think
- The value (0-100) needs to move the element
- The `translateY: ` property was added, to move the element, because it is animatable
- The value of the custom property was called: `translateY(var(--bottom))` 
- _Since there was no var() call, the custom property was assigned to the element but was never used in a style property_
- Finally, to make the value negative, since we are moving the element up the Y-axis, and to ensure it corresponds  to a proper distance in the play area, a calc() was used: `transform: translateY(calc(var(--bottom) * -0.7vh));`
- Play around with the number to make it more or less responsive
- BTW, The element had a `top: 500px` value assigned, which was also removed and replaced with a `bottom: 40px`

**Comment by beutnagel** [comment]
I had forked your repository, so to add the code changes I made, please merge the pull request.
